-- 07_payment_proofs_storage.sql
-- Fixes guest checkout: the storage.upload() call in /checkout was failing
-- because the "payment-proofs" bucket has no INSERT policy for anon or
-- authenticated users. When the upload threw, the surrounding catch cleared
-- the cart and no order was written.
--
-- Guest uploads go under a "guest/<random>.<ext>" path, and signed-in users
-- under "<user_id>/<random>.<ext>".  Staff need to be able to read them from
-- the admin dashboard (via signed URLs generated by service-role code) but
-- nobody except staff should be able to list or download.

begin;

-- Ensure RLS is on (Supabase defaults it on, but be explicit).
alter table storage.objects enable row level security;

-- Clean up older policies with the same names so this file is idempotent.
drop policy if exists "payment_proofs anon insert"        on storage.objects;
drop policy if exists "payment_proofs auth insert"        on storage.objects;
drop policy if exists "payment_proofs staff read"         on storage.objects;
drop policy if exists "payment_proofs staff manage"       on storage.objects;
drop policy if exists "payment_proofs owner read"         on storage.objects;

-- Anonymous checkout: allow guests to upload into the bucket.
create policy "payment_proofs anon insert"
on storage.objects
for insert
to anon
with check (bucket_id = 'payment-proofs');

-- Signed-in checkout: allow uploads into the bucket. (The app already puts
-- them under a folder named after the user id, so this scoping is enforced
-- client-side; RLS just needs to permit the write.)
create policy "payment_proofs auth insert"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'payment-proofs');

-- Signed-in customer can read their own proofs (folder = user_id).
create policy "payment_proofs owner read"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'payment-proofs'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Staff (admin / moderator) can list and download any proof for review.
create policy "payment_proofs staff read"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'payment-proofs'
  and public.is_staff(auth.uid())
);

-- Staff can also update / delete (e.g. cleanup) if needed.
create policy "payment_proofs staff manage"
on storage.objects
for all
to authenticated
using (
  bucket_id = 'payment-proofs'
  and public.is_staff(auth.uid())
)
with check (
  bucket_id = 'payment-proofs'
  and public.is_staff(auth.uid())
);

commit;
